"""
core/reporting/html_renderer.py
==================================
Renders a forensic ReportData object to a self-contained HTML file.

Uses Python's built-in string templating (no Jinja2 dependency required at
runtime) so the tool remains portable.  The HTML is fully self-contained:
all CSS and JS are inlined — a single file the investigator can archive
and open offline.
"""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models.report_data import ReportData

from utils.logger import get_logger

log = get_logger(__name__)

# Evidence type → CSS class name
_BADGE_CLASS = {
    "DIRECT":     "badge-direct",
    "CORRELATED": "badge-correlated",
    "INFERRED":   "badge-inferred",
}

# Severity → CSS class name
_SEVERITY_CLASS = {
    "NORMAL":     "sev-normal",
    "IMPORTANT":  "sev-important",
    "SUSPICIOUS": "sev-suspicious",
}

# Flag → human-readable label
_FLAG_LABELS = {
    "ACTIVITY_GAP":             "⏱️ Activity Gap (Blackout)",
    "TEMPORAL_INTEGRITY_INVALID": "❌ Temporal Integrity Failure",
    "SUSPICIOUS":               "🚩 Suspicious Behavioral Hit",
    
    # Intelligence Layer Markers
    "HEAVY_USAGE":              "⚡ Intense Activity Window",
    "APP_LIFECYCLE":            "🧬 App Lifecycle Confirmed",
    "DORMANT_APP":              "💤 Dormant Application",
    
    "LIFECYCLE_CORRELATED":     "🧬 Lifecycle Correlation",
    "SUSPICIOUS_REMOVAL":       "🚨 Suspicious App Removal",
    "BACKGROUND_ACTIVITY_DETECTED": "🌑 Background Activity Risk",
    
    # Intelligence Layer Markers (Rules 4-10)
    "LATE_NIGHT_ACTIVITY":      "🌙 Late Night Activity",
    "IMMEDIATE_APP_USE":        "⚡ Immediate App Use",
    "COMMUNICATION_BURST":      "💬 Communication Burst",
    "SILENT_BACKGROUND_SERVICE": "🌑 Silent Background Service",
    "RAPID_INSTALL_UNINSTALL":  "🔄 Rapid Install/Uninstall",
    "ANTI_FORENSIC_SEQUENCE":   "🧹 Anti-Forensic Sequence",
    "FACTORY_RESET_INDICATOR":  "☣️ Factory Reset Indicator",
}


def _format_duration(seconds: float) -> str:
    """Format seconds into a human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{int(seconds // 60)}m"
    else:
        return f"{int(seconds // 3600)}h {int((seconds % 3600) // 60)}m"


class HtmlRenderer:
    """Renders a :class:`ReportData` to a self-contained HTML file."""

    def render(self, data: ReportData, output_path: Path) -> None:
        html_content = self._build_html(data)
        output_path.write_text(html_content, encoding="utf-8")
        log.info("HTML report: %d bytes -> %s", len(html_content.encode()), output_path)

    def _build_html(self, d: ReportData) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DroidTrace Pro – Forensic Report | {d.device.serial}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="header">
  <div class="header-brand">
    <span class="logo">🔬</span>
    <div>
      <h1>DroidTrace Pro</h1>
      <p class="subtitle">Android Forensic Analysis Report</p>
    </div>
  </div>
  <div class="header-meta">
    <span>Report generated: {d.report_time.strftime('%Y-%m-%d %H:%M:%S UTC')}</span><br>
    <span>Tool version: v{d.tool_version}</span>
  </div>
</div>

<div class="container">
  {self._device_card(d)}
  {self._behavioral_profile_section(d)}
  {self._summary_cards(d)}
  {self._flag_summary_section(d)}
  {self._suspicious_apps_section(d)}
  {self._network_usage_section(d)}
  {self._timeline_section(d)}
  {self._sessions_section(d)}
  {self._inferred_section(d)}

  <footer class="footer">
    Generated by DroidTrace Pro v{d.tool_version} &mdash;
    Collection: {d.collection_time.strftime('%Y-%m-%d %H:%M:%S UTC')} &mdash;
    {len(d.timeline)} events analysed
  </footer>
</div>
<script>{_JS}</script>
</body>
</html>"""

    def _device_card(self, d: ReportData) -> str:
        dev = d.device
        rows = [
            ("Serial", dev.serial),
            ("Model", f"{dev.manufacturer} {dev.model}"),
            ("Android Version", dev.android_version),
            ("API Level", str(dev.sdk_version)),
            ("Build Fingerprint", f'<code>{dev.build_fingerprint}</code>'),
            ("Transport", dev.transport_type.upper()),
            ("Collection Time", d.collection_time.strftime("%Y-%m-%d %H:%M:%S UTC")),
        ]
        rows_html = "".join(f'<tr><td class="prop-key">{k}</td><td>{v}</td></tr>' for k, v in rows)
        return f"""
<section class="card">
  <h2>📱 Device Information</h2>
  <table class="prop-table">{rows_html}</table>
</section>"""

    def _behavioral_profile_section(self, d: ReportData) -> str:
        if not d.behavioral_summary:
            return ""
        s = d.behavioral_summary
        summary = s.to_dict()
        top_apps_html = "".join(
            f'<tr><td><code>{html.escape(app)}</code></td><td class="text-right"><code>{_format_duration(dur)}</code></td></tr>'
            for app, dur in s.top_apps_by_duration
        )
        return f"""
<section class="card">
  <h2>🧠 Behavioral User Profile</h2>
  <div class="profile-grid">
    <div class="profile-main">
      <table class="prop-table">
        <tr><td class="prop-key">Active Window</td><td><span class="badge badge-inferred">{summary['active_window']}</span></td></tr>
        <tr><td class="prop-key">Total Active Duration</td><td><strong>{_format_duration(summary['total_active_time_sec'])}</strong></td></tr>
        <tr><td class="prop-key">Total Sessions</td><td>{summary['session_count']}</td></tr>
        <tr><td class="prop-key">Activity Gaps</td><td>{summary['gap_count']} detections</td></tr>
        <tr><td class="prop-key">Forensic Rules Applied</td><td>{len(d.stats.get('inference', {}).get('rules_applied', []))} rules</td></tr>
        <tr><td class="prop-key">Total Inferred Detections</td><td><strong>{d.stats.get('inference', {}).get('inferred_added', 0)}</strong></td></tr>
      </table>
    </div>
    <div class="profile-side">
      <h3>Most Used Applications</h3>
      <table class="prop-table">{top_apps_html}</table>
    </div>
  </div>
</section>"""

    def _summary_cards(self, d: ReportData) -> str:
        cards = [
            ("📋", "Total Events",      len(d.timeline),          ""),
            ("🔗", "Correlated",        len(d.correlated_events),  "accent-blue"),
            ("🧠", "Inferred",          len(d.inferred_events),    "accent-purple"),
            ("⚑",  "Flagged Events",   len(d.flagged_events),     "accent-orange"),
            ("🎯", "Suspicious Apps",   len(d.suspicious_apps),    "accent-red"),
        ]
        cards_html = "".join(
            f'<div class="stat-card {cls}">'
            f'<span class="stat-icon">{icon}</span>'
            f'<span class="stat-value">{val}</span>'
            f'<span class="stat-label">{label}</span>'
            f'</div>'
            for icon, label, val, cls in cards
        )
        return f'<div class="stats-row">{cards_html}</div>'

    def _flag_summary_section(self, d: ReportData) -> str:
        if not d.flag_summary:
            return ""
        items = sorted(d.flag_summary.items(), key=lambda x: -x[1])
        bars = ""
        max_count = max(c for _, c in items) or 1
        for flag, count in items:
            label = _FLAG_LABELS.get(flag, flag.replace("_", " ").title())
            pct = int(count / max_count * 100)
            bars += f"""
<div class="flag-bar-row">
  <span class="flag-label">{label}</span>
  <div class="flag-bar-track">
    <div class="flag-bar-fill" style="width:{pct}%"></div>
  </div>
  <span class="flag-count">{count}</span>
</div>"""
        return f"""
<section class="card collapsible">
  <h2 class="collapse-trigger" onclick="toggle(this)">⚑ Behavioral Flag Summary
    <span class="toggle-icon">▼</span>
  </h2>
  <div class="collapse-body">{bars}</div>
</section>"""

    def _suspicious_apps_section(self, d: ReportData) -> str:
        if not d.suspicious_apps:
            return ""
        pills = "".join(f'<span class="app-pill">{html.escape(a)}</span>' for a in d.suspicious_apps)
        return f"""
<section class="card collapsible">
  <h2 class="collapse-trigger" onclick="toggle(this)">🎯 Suspicious Applications
    <span class="toggle-icon">▼</span>
  </h2>
  <div class="collapse-body"><div class="pill-row">{pills}</div></div>
</section>"""

    def _network_usage_section(self, d: ReportData) -> str:
        net_events = [e for e in d.timeline if e.event_type == "NETWORK_USAGE"]
        if not net_events:
            return ""
        
        # Aggregate by app
        usage: dict[str, dict[str, int]] = {}
        for e in net_events:
            app = e.app
            if app not in usage:
                usage[app] = {"rx": 0, "tx": 0}
            usage[app]["rx"] += e.raw_fields.get("bytes_rx", 0)
            usage[app]["tx"] += e.raw_fields.get("bytes_tx", 0)

        rows = ""
        for app, bytes_info in sorted(usage.items(), key=lambda x: -(x[1]["tx"] + x[1]["rx"])):
            rx_kb = bytes_info["rx"] / 1024
            tx_kb = bytes_info["tx"] / 1024
            total_kb = rx_kb + tx_kb
            
            rows += f"""
<tr>
  <td class="mono">{html.escape(app)}</td>
  <td class="text-right"><code>{rx_kb:.1f} KB</code></td>
  <td class="text-right"><code>{tx_kb:.1f} KB</code></td>
  <td class="text-right"><strong>{total_kb:.1f} KB</strong></td>
</tr>"""

        return f"""
<section class="card collapsible">
  <h2 class="collapse-trigger" onclick="toggle(this)">📡 Per-App Network Usage Summary
    <span class="badge-count">{len(usage)} apps recorded</span>
    <span class="toggle-icon">▼</span>
  </h2>
  <div class="collapse-body table-scroll">
    <table class="data-table">
      <thead>
        <tr>
          <th>Application Package</th>
          <th class="text-right">Received (RX)</th>
          <th class="text-right">Transmitted (TX)</th>
          <th class="text-right">Total Data</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  </div>
</section>"""

    def _timeline_section(self, d: ReportData) -> str:
        rows = ""
        for e in d.timeline:
            badge_cls = _BADGE_CLASS.get(e.evidence_type, "badge-direct")
            sev_cls = _SEVERITY_CLASS.get(e.severity, "sev-normal")
            flag_pills = "".join(f'<span class="flag-pill">{_FLAG_LABELS.get(f, f)}</span>' for f in e.flags)
            row_cls = "row-flagged" if e.flags or e.severity == "SUSPICIOUS" else ""
            
            reason_html = f'<div class="event-reason">Forensic Reasoning: {html.escape(e.reason)}</div>' if e.reason else ""
            
            rows += f"""
<tr class="{row_cls}">
  <td class="mono">{e.sequence_index}</td>
  <td class="mono ts">{e.iso_timestamp}</td>
  <td><span class="badge {badge_cls}">{e.evidence_type}</span></td>
  <td><span class="sev-badge {sev_cls}">{e.severity}</span></td>
  <td class="mono">{html.escape(e.app)}</td>
  <td>{e.event_type}</td>
  <td class="desc">
    <div class="event-desc">{html.escape(e.description)}</div>
    {reason_html}
  </td>
  <td>{flag_pills}</td>
</tr>"""

        return f"""
<section class="card collapsible">
  <h2 class="collapse-trigger" onclick="toggle(this)">📅 Full Timeline
    <span class="badge-count">{len(d.timeline)} events</span>
    <span class="toggle-icon">▼</span>
  </h2>
  <div class="collapse-body table-scroll">
    <table class="data-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Timestamp (UTC)</th>
          <th>Evidence</th>
          <th>Severity</th>
          <th>Package</th>
          <th>Event Type</th>
          <th>Description & Reasoning</th>
          <th>Flags</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  </div>
</section>"""

    def _sessions_section(self, d: ReportData) -> str:
        sessions = [e for e in d.timeline if e.event_type == "APP_SESSION"]
        if not sessions:
            return ""
        
        rows = ""
        for s in sessions:
            dur = s.raw_fields.get("duration_sec", 0)
            stype = s.raw_fields.get("session_type", "EXACT")
            sev_cls = _SEVERITY_CLASS.get(s.severity, "sev-normal")
            
            rows += f"""
<tr>
  <td class="mono ts">{s.iso_timestamp}</td>
  <td class="mono">{html.escape(s.app)}</td>
  <td><strong>{_format_duration(dur)}</strong></td>
  <td><span class="badge badge-inferred">{stype}</span></td>
  <td><span class="sev-badge {sev_cls}">{s.severity}</span></td>
  <td class="desc">
    <div class="event-desc">{html.escape(s.description)}</div>
    <div class="event-reason">{html.escape(s.reason)}</div>
  </td>
</tr>"""

        return f"""
<section class="card collapsible">
  <h2 class="collapse-trigger" onclick="toggle(this)">📊 User Activity Sessions
    <span class="badge-count">{len(sessions)} sessions</span>
    <span class="toggle-icon">▼</span>
  </h2>
  <div class="collapse-body table-scroll">
    <table class="data-table">
      <thead>
        <tr>
          <th>Start Time</th>
          <th>Application</th>
          <th>Duration</th>
          <th>Boundary</th>
          <th>Severity</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  </div>
</section>"""

    def _inferred_section(self, d: ReportData) -> str:
        if not d.inferred_events:
            return ""
        rows = ""
        for e in d.inferred_events:
            sev_cls = _SEVERITY_CLASS.get(e.severity, "sev-normal")
            flag_pills = "".join(f'<span class="flag-pill">{_FLAG_LABELS.get(f, f)}</span>' for f in e.flags)
            reason_html = f'<div class="event-reason">Forensic Reasoning: {html.escape(e.reason)}</div>' if e.reason else ""
            
            rows += f"""
<tr>
  <td class="mono ts">{e.iso_timestamp}</td>
  <td><span class="sev-badge {sev_cls}">{e.severity}</span></td>
  <td>{e.event_type}</td>
  <td class="desc">
    <div class="event-desc">{html.escape(e.description)}</div>
    {reason_html}
  </td>
  <td>{flag_pills}</td>
</tr>"""
        return f"""
<section class="card collapsible">
  <h2 class="collapse-trigger" onclick="toggle(this)">🧠 Inferred Events &amp; Detections
    <span class="badge-count">{len(d.inferred_events)} detections</span>
    <span class="toggle-icon">▼</span>
  </h2>
  <div class="collapse-body">
    <div class="table-scroll">
      <table class="data-table">
        <thead><tr>
          <th>Timestamp</th><th>Severity</th><th>Detection Type</th>
          <th>Description & Reasoning</th><th>Flags</th>
        </tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </div>
  </div>
</section>"""


_CSS = """
:root {
  --bg:       #0f1117;
  --surface:  #1a1d27;
  --surface2: #22263a;
  --border:   #2e344a;
  --text:     #e2e8f0;
  --muted:    #8892a4;
  --accent:   #6366f1;
  --blue:     #3b82f6;
  --purple:   #a855f7;
  --orange:   #f97316;
  --red:      #ef4444;
  --green:    #22c55e;
  --yellow:   #eab308;
  --radius:   10px;
  --shadow:   0 4px 24px rgba(0,0,0,0.4);
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; font-size: 14px; }
code { font-family: 'Cascadia Code', 'Consolas', monospace; font-size: 12px; }

.header {
  background: linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #1e1b4b 100%);
  border-bottom: 1px solid var(--border);
  padding: 24px 40px;
  display: flex; justify-content: space-between; align-items: center;
}
.header-brand { display: flex; align-items: center; gap: 16px; }
.logo { font-size: 40px; }
h1 { font-size: 26px; font-weight: 700; letter-spacing: -0.5px; }
.subtitle { color: var(--muted); font-size: 13px; margin-top: 2px; }
.header-meta { color: var(--muted); font-size: 12px; text-align: right; line-height: 1.8; }

.container { max-width: 1600px; margin: 0 auto; padding: 32px 40px; }

.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 24px;
  margin-bottom: 20px;
  box-shadow: var(--shadow);
}
.card h2 { font-size: 16px; font-weight: 600; margin-bottom: 16px;
  display: flex; align-items: center; gap: 8px; cursor: default; }
.collapse-trigger { cursor: pointer; user-select: none; }
.collapse-trigger:hover { color: var(--accent); }
.toggle-icon { margin-left: auto; font-size: 12px; color: var(--muted); }
.collapse-body { animation: fadeIn 0.2s ease; }
@keyframes fadeIn { from { opacity:0; transform:translateY(-4px); } to { opacity:1; transform:none; } }

.stats-row { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 20px; }
.stat-card {
  flex: 1; min-width: 140px;
  background: var(--surface2);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 20px 16px;
  display: flex; flex-direction: column; align-items: center; gap: 6px;
}
.stat-icon { font-size: 28px; }
.stat-value { font-size: 32px; font-weight: 700; }
.stat-label { font-size: 11px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }
.accent-blue  .stat-value { color: var(--blue); }
.accent-purple .stat-value { color: var(--purple); }
.accent-orange .stat-value { color: var(--orange); }
.accent-red   .stat-value { color: var(--red); }

.prop-table { width: 100%; border-collapse: collapse; }
.prop-table tr + tr { border-top: 1px solid var(--border); }
.prop-table td { padding: 8px 12px; vertical-align: top; }
.prop-key { color: var(--muted); width: 180px; font-size: 12px; }

.table-scroll { overflow-x: auto; }
.data-table { width: 100%; border-collapse: collapse; font-size: 12px; }
.data-table thead { background: var(--surface2); position: sticky; top: 0; z-index: 1; }
.data-table th { padding: 10px 12px; text-align: left; color: var(--muted);
  font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px;
  border-bottom: 1px solid var(--border); white-space: nowrap; }
.data-table td { padding: 8px 12px; border-bottom: 1px solid var(--border);
  vertical-align: top; }
.data-table tr:hover td { background: var(--surface2); }
.row-flagged td { border-left: 3px solid var(--orange); }
.mono { font-family: 'Cascadia Code', monospace; }
.ts { white-space: nowrap; color: var(--muted); font-size: 11px; }
.desc { color: var(--muted); font-size: 12px; max-width: 450px; }

.badge {
  display: inline-block; padding: 2px 8px; border-radius: 20px;
  font-size: 10px; font-weight: 600; text-transform: uppercase; white-space: nowrap;
}
.badge-direct     { background: rgba(34,197,94,0.15);  color: var(--green); }
.badge-correlated { background: rgba(59,130,246,0.15); color: var(--blue); }
.badge-inferred   { background: rgba(168,85,247,0.15); color: var(--purple); }
.badge-count { font-size: 11px; color: var(--muted); margin-left: 8px;
  background: var(--surface2); padding: 2px 8px; border-radius: 20px; }

.sev-badge {
    display: inline-block; padding: 2px 8px; border-radius: 4px;
    font-size: 10px; font-weight: 700; text-transform: uppercase;
}
.sev-normal { background: rgba(136,146,164,0.1); color: var(--muted); }
.sev-important { background: rgba(59,130,246,0.15); color: var(--blue); }
.sev-suspicious { background: rgba(239,68,68,0.15); color: var(--red); }

.flag-pill {
  display: inline-block; margin: 2px;
  padding: 2px 8px; border-radius: 20px;
  background: rgba(249,115,22,0.15); color: var(--orange);
  font-size: 10px; font-weight: 600; white-space: nowrap;
}
.app-pill {
  display: inline-block; margin: 4px;
  padding: 4px 12px; border-radius: 20px;
  background: var(--surface2); border: 1px solid var(--border);
  font-family: monospace; font-size: 12px; color: var(--red);
}
.pill-row { display: flex; flex-wrap: wrap; }

.flag-bar-row { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
.flag-label { width: 240px; font-size: 12px; flex-shrink: 0; }
.flag-bar-track { flex: 1; height: 8px; background: var(--surface2); border-radius: 4px; overflow: hidden; }
.flag-bar-fill { height: 100%; background: var(--orange); border-radius: 4px; transition: width 0.4s ease; }
.flag-count { width: 32px; text-align: right; color: var(--muted); font-size: 12px; }

.profile-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
.profile-side h3 { font-size: 12px; text-transform: uppercase; color: var(--muted); margin-bottom: 12px; }
.text-right { text-align: right; }

.event-reason {
    margin-top: 6px; padding: 8px; background: rgba(0,0,0,0.2);
    border-radius: 4px; font-size: 11px; border-left: 2px solid var(--accent);
    color: var(--text); font-style: italic;
}

.footer {
  border-top: 1px solid var(--border);
  padding: 20px 0; text-align: center;
  color: var(--muted); font-size: 12px; margin-top: 8px;
}
"""

_JS = """
function toggle(trigger) {
  const body = trigger.parentElement.querySelector('.collapse-body');
  const icon = trigger.querySelector('.toggle-icon');
  if (!body) return;
  const hidden = body.style.display === 'none';
  body.style.display = hidden ? '' : 'none';
  if (icon) icon.textContent = hidden ? '▼' : '▶';
}
"""
